### ISSUE TITLE
Examples contains only 1 (simple) example

### ISSUE THREAD

**Issue by rouvoy** [Spirals-Team/reactive-slides#3]
Can't you include several examples, one of these being the reveal.js demo slides ?

**Comment by rbadr** [comment]
The main example already contains all the reveal.js demo slides. We can reorganize the slides in 3 parts (Interactive - reveal.js demo slides - our own presentation ) so that it would be more visible and clear. What do you think ? And should it be in this order ?

**Comment by rouvoy** [comment]
Yes, please organise the `examples` directory into 3 folders, each containing one presentation. Not all of them have to demonstrate the interactive features (_e.g._, reveal.js content can be kept as it is).

**Comment by rbadr** [comment]
Yes, for sure, we will amend this issue. Thanks for the feedback !

**Comment by rouvoy** [comment]
I merged the pull request, but I expected *and mentioned* three separate *folders* to split the three presentations.

**Comment by rbadr** [comment]
Just created a new pull request with the correct modifications, each presentation is located in a folder ( with its controllers and views)

It should be good now. Can you confirm ?
